name: Backup Job

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  my_job:
    name: Create backup files using GitHub Actions runtime and predefined script
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"

      - name: Verify Python Installation
        run: |
          python --version
          pip --version

      - name: Generate Centralized UTC Timestamp
        run: |
          echo "RUN_TS=$(TZ=Asia/Kolkata date +"%Y-%m-%d_%H-%M-%S")" >> $GITHUB_ENV

      - name: Run Backup Script
        run: |
          python backup_file_prep.py

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload Backup File to Azure Blob Storage
        run: |
          az storage blob upload \
            --account-name sourcedlsbackupvaultpoc \
            --container-name raw \
            --name backup_poc_source_file_${RUN_TS}.json \
            --file backup_poc_source_file_${RUN_TS}.json \
            --auth-mode login \
            --overwrite true

      
